# default config.yml

#Set true for debugging messages and 100% drop of keys and random items.
debugging: false
set-time: night
stop-time: true
max-team-size: 6
#mob or player sets where items are dropped after killing a mob
items-drop-to: player
#mob or player sets where keys are dropped after killing a mob
keys-drop-to: player
default-pvp-on: false
leaving-team-takes-to-spawn: true
creating-team-takes-to-spawn: false
#mobs that drop items
item-dropping-mobs:
  - SKELETON
  - ZOMBIE
  - PIG
  - CAVE_SPIDER
  - SPIDER
#Mobs that drop keys, 1 in X probability key will drop.
key-dropping-mobs:
  - ZOMBIE
  - 10
  - ILLUSIONER
  - 2
  - SKELETON
  - 12
  - ENDERMITE
  - 10
  - SPIDER
  - 12
  - CAVE_SPIDER
  - 13
  - WITHER_SKELETON
  - 4
#items the above mobs will drop,
#Item name, 1/X chance of a drop (1 to 100%), quantity of items dropped
mob-drops:
  - ARROW
  - 10
  - 4
  - APPLE
  - 20
  - 1
  - MAP
  - 50
  - 1
#Boss mobs boosts: Mob, HP Regen per hit, Damage addition, Thornmail (returns damage to sender) [1 = .5 hearts]
boss-mobs:
  - GIANT
  - 2
  - 0
  - 1
  - DRAGON
  - 0
  - 4
  - 2
  
#Books are keys, remove book from list if you do not want players to share keys.
dropping-whitelist:
  - BOOK
  - ARROW
  - SPECTRAL_ARROW
  - ARROW_OF_NIGHT_VISION
  - ARROW_OF_INVISIBILITY
  - ARROW_OF_LEAPING
  - ARROW_OF_FIRE_RESISTANCE
  - ARROW_OF_SWIFTNESS
  - ARROW_OF_SLOWNESS
  - ARROW_OF_THE_TURTLE_MASTER
  - ARROW_OF_BREATHING
  - ARROW_OF_HEALING
  - ARROW_OF_HARMING
  - ARROW_OF_POISON
  - ARROW_OF_REGENERATION
  - ARROW_OF_STRENGTH
  - ARROW_OF_WEAKNESS
  - ARROW_OF_LUCK
  - ARROW_OF_SLOW_FALLING
  - POTION_OF_NIGHT_VISION
  - POTION_OF_INVISIBILITY
  - POTION_OF_LEAPING
  - POTION_OF_FIRE_RESISTANCE
  - POTION_OF_SWIFTNESS
  - POTION_OF_SLOWNESS
  - POTION_OF_THE_TURTLE_MASTER
  - POTION_OF_WATER_BREATHING
  - POTION_OF_HEALING
  - POTION_OF_HARMING
  - POTION_OF_POISON
  - POTION_OF_REGENERATION
  - POTION_OF_STRENGTH
  - POTION_OF_WEAKNESS
  - POTION_OF_LUCK
  - POTION_OF_SLOW_FALLING
  - SPLASH_WATER_BOTTLE
  - FISHING_ROD
  - FLINT_AND_STEEL
  - COMPASS
  - LEAD
  - CLOCK
  - TORCH
  - REDSTONE_TORCH
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - RAW_PORKCHOP
  - COOKED_PORKCHOP
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - RAW_COD
  - RAW_SALMON
  - TROPICAL_FISH
  - PUFFERFISH
  - COOKED_COD
  - COOK_SALMON
  - CAKE
  - COOKIE
  - MELON_SLICE
  - DRIED_KELP
  - RAW_BEEF
  - COOKED_BEEF
  - RAW_CHICKEN
  - COOKED_CHICKEN
  - ROTTEN_FLESH
  - SPIDER_EYE
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - RAW_RABBIT
  - COOKED_RABBIT
  - RABBIT_STEW
  - RAW_MUTTON
  - COOKED_MUTTON
  - BEETROOT
  - BEETROOT_SOUP
  - MAP
guide-title: Mineswarm Guide
guide-author: Cutrats110
guide-pages:
  - This is page one
  - This is on page two...t
tank-potions-disabled-mobs:
  - Healing
tank-potions-disabled-players:
  - Poison
mage-potions-disabled-mobs:
  - Poison
mage-potions-disabled-players:
  - Healing
  - Healing 2
#Class items, one per line
mage-class:
  - LEATHER_HELMET,1
  - LEATHER_CHESTPLATE,1
  - LEATHER_LEGGINGS,1
  - LEATHER_BOOTS,1
  - BLAZE_ROD,1,SHARPNESS,3,FIRE_ASPECT,2
  - 1903,2
  - 19035,2
  - 19015,4
  - 19022,4
  - 19033,4
  - 1904,2
  - 19011,1
archer-class:
  - LEATHER_HELMET,1
  - LEATHER_CHESTPLATE,1
  - LEATHER_LEGGINGS,1
  - LEATHER_BOOTS,1,FEATHER_FALLING,3
  - BOW,1,POWER,1
  - WOODEN_SWORD,1,SHARPNESS,1
  - SPECTRAL_ARROW,20
  - ARROW,52
  - 15,1
  - 4,1
aquadic-class:
  - TURTLE_HELMET,1
  - LEATHER_LEGGINGS,1
  - CHAINMAIL_CHESTPLATE,1
  - LEATHER_BOOTS,1,DEPTH_STRIDER,3
  - 29,2
  - 20,2
  - TRIDENT,1,RIPTIDE,3
  - TRIDENT,1,LOYALTY,1
adc-class:
  - IRON_CHESTPLATE,1
  - CHAINMAIL_HELMET,1
  - CHAINMAIL_LEGGINGS,1
  - CHAINMAIL_BOOTS,1
  - IRON_SWORD,1,SHARPNESS,1,UNBREAKING,1
  - 29,2
solo-class:
  - STICK,1,KNOCK_BACK,2
  - BOOK,1
  - ARROW,20
  - WOODEN_SWORD,1,KNOCKBACK,2
  - WOODEN_SWORD,1,KNOCKBACK,2,SHARPNESS,2
  - SPECTRAL_ARROW,10
tank-class:
  - IRON_HELMET,1
  - DIAMOND_CHESTPLATE,1
  - IRON_LEGGINGS,1
  - IRON_BOOTS,1
  - SHIELD,1
  - STONE_AXE,1,UNBREAKING,3
  - GOLDEN_APPLE,3
